In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.7.4.5)
Requirement already satisfied: bleach in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2025.6.15)
Requirement already satisfied: charset-normalizer in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (6.31.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (0.5.1)

In [8]:
!kaggle datasets download ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading retail-orders.zip to /Users/amruthaduvvuri
  0%|                                                | 0.00/200k [00:00<?, ?B/s]
100%|█████████████████████████████████████████| 200k/200k [00:00<00:00, 271MB/s]

In [11]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('retail-orders.zip') 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [12]:
import pandas as pd

df = pd.read_csv("orders.csv")
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [13]:
df['Ship Mode'].unique() #reading how many uniques values that is distinct values are present

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [14]:
#convert not available , unknown as null 
df = pd.read_csv('orders.csv',na_values =['Not Available','unknown'])
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [15]:
#rename columns names ..make them lower case and replace space with underscore
#df.rename(columns={'Order Id':'order_id', 'City':'city'})
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [16]:
#derive new columns discount , sale price and profit 
df['discount'] =df['list_price']*df['discount_percent']*.01 
df['sale_price'] = df['list_price']- df['discount']
df['profit']= df['sale_price']- df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [17]:
#check the datatypes for consistency 
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [18]:
#convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [19]:
#drop cost_price , list_price and discount_percent columns 
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

In [40]:
!pip install pymysql #-connector-python

Requirement already satisfied: pymysql in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.1.1)

In [48]:
import pandas as pd
from sqlalchemy import create_engine

In [42]:
conda install -c conda-forge pymysql

Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - pymysql


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2025.6.15  |       hbd8a1cb_0         148 KB  conda-forge
    certifi-2025.6.15          |     pyhd8ed1ab_0         152 KB  conda-forge
    conda-24.11.3              |  py312h81bd7bf_0         1.1 MB  conda-forge
    libexpat-2.6.3             |       hf9b8971_0          62 KB  conda-forge
    libsqlite-3.46.0           |       hfb93653_0         811 KB  conda-forge
    libzlib-1.2.13             |       hfb2fe0b_6          46 KB  conda-forge
    openssl-3.5.0              |       h81ee809_1         2.9 MB  conda-forge
    pymysql-1.1.1              |     pyhd8ed1ab_1          43 KB  conda-forge
    python-3.12.2              |hdf0ec26_0_cpython        12.5 MB  conda-forge
    python_abi-3.12            |          7_cp312           7 KB  conda-forge
    zlib-1.2.13                |       hfb2fe0b_6          76 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        17.8 MB

The following NEW packages will be INSTALLED:

  libexpat           conda-forge/osx-arm64::libexpat-2.6.3-hf9b8971_0
  libsqlite          conda-forge/osx-arm64::libsqlite-3.46.0-hfb93653_0
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-hfb2fe0b_6
  pymysql            conda-forge/noarch::pymysql-1.1.1-pyhd8ed1ab_1
  python_abi         conda-forge/noarch::python_abi-3.12-7_cp312

The following packages will be UPDATED:

  ca-certificates    pkgs/main/osx-arm64::ca-certificates-~ --> conda-forge/noarch::ca-certificates-2025.6.15-hbd8a1cb_0
  certifi            pkgs/main/osx-arm64::certifi-2025.4.2~ --> conda-forge/noarch::certifi-2025.6.15-pyhd8ed1ab_0
  openssl              pkgs/main::openssl-3.0.16-h02f6b3c_0 --> conda-forge::openssl-3.5.0-h81ee809_1
  zlib                    pkgs/main::zlib-1.2.13-h18a0788_1 --> conda-forge::zlib-1.2.13-hfb2fe0b_6

The following packages will be SUPERSEDED by a higher-priority channel:

  conda              pkgs/main::conda-24.11.3-py312hca03da~ --> conda-forge::conda-24.11.3-py312h81bd7bf_0
  python                pkgs/main::python-3.12.7-h99e199e_0 --> conda-forge::python-3.12.2-hdf0ec26_0_cpython



Downloading and Extracting Packages:
python-3.12.2        | 12.5 MB   |                                       |   0%
openssl-3.5.0        | 2.9 MB    |                                       |   0%

conda-24.11.3        | 1.1 MB    |                                       |   0%


libsqlite-3.46.0     | 811 KB    |                                       |   0%



certifi-2025.6.15    | 152 KB    |                                       |   0%




ca-certificates-2025 | 148 KB    |                                       |   0%





zlib-1.2.13          | 76 KB     |                                       |   0%






libexpat-2.6.3       | 62 KB     |                                       |   0%







libzlib-1.2.13       | 46 KB     |                                       |   0%








pymysql-1.1.1        | 43 KB     |                                       |   0%









python_abi-3.12      | 7 KB      |                                       |   0%
openssl-3.5.0        | 2.9 MB    | 1                                     |   1%

conda-24.11.3        | 1.1 MB    | 5                                     |   1%


libsqlite-3.46.0     | 811 KB    | 7                                     |   2%



certifi-2025.6.15    | 152 KB    | ###9                                  |  11%



certifi-2025.6.15    | 152 KB    | ##################################### | 100%



certifi-2025.6.15    | 152 KB    | ##################################### | 100%
openssl-3.5.0        | 2.9 MB    | ######1                               |  17%

conda-24.11.3        | 1.1 MB    | ########2                             |  22%


python-3.12.2        | 12.5 MB   |                                       |   0%




python-3.12.2        | 12.5 MB   | ##4                                   |   7%


libsqlite-3.46.0     | 811 KB    | ###############3                      |  41%




ca-certificates-2025 | 148 KB    | ################                      |  43%

conda-24.11.3        | 1.1 MB    | ##########8                           |  29%

conda-24.11.3        | 1.1 MB    | #################                     |  46%

python-3.12.2        | 12.5 MB   | ####4                                 |  12%

conda-24.11.3        | 1.1 MB    | ##########################8           |  72%




ca-certificates-2025 | 148 KB    | ############################          |  76%


libsqlite-3.46.0     | 811 KB    | #################5                    |  47%

conda-24.11.3        | 1.1 MB    | ###############################9      |  86%


libsqlite-3.46.0     | 811 KB    | ##################9                   |  51%


libsqlite-3.46.0     | 811 KB    | #############################2        |  79%


libsqlite-3.46.0     | 811 KB    | #################################5    |  91%


libsqlite-3.46.0     | 811 KB    | ##################################### | 100%


libsqlite-3.46.0     | 811 KB    | ##################################### | 100%





zlib-1.2.13          | 76 KB     | #######7                              |  21%





zlib-1.2.13          | 76 KB     | ##################################### | 100%





python-3.12.2        | 12.5 MB   | ####9                                 |  13%






libexpat-2.6.3       | 62 KB     | #########4                            |  26%






libexpat-2.6.3       | 62 KB     | ##################################### | 100%






python-3.12.2        | 12.5 MB   | #####9                                |  16%







python-3.12.2        | 12.5 MB   | ######3                               |  17%







libzlib-1.2.13       | 46 KB     | ##################################### | 100%







libzlib-1.2.13       | 46 KB     | ##################################### | 100%







libzlib-1.2.13       | 46 KB     | ##################################### | 100%








pymysql-1.1.1        | 43 KB     | #############6                        |  37%








pymysql-1.1.1        | 43 KB     | ##################################### | 100%








pymysql-1.1.1        | 43 KB     | ##################################### | 100%




ca-certificates-2025 | 148 KB    | ################################1     |  87%









python_abi-3.12      | 7 KB      | ##################################### | 100%









python_abi-3.12      | 7 KB      | ##################################### | 100%









python_abi-3.12      | 7 KB      | ##################################### | 100%




ca-certificates-2025 | 148 KB    | ##################################### | 100%




ca-certificates-2025 | 148 KB    | ##################################### | 100%




ca-certificates-2025 | 148 KB    | ##################################### | 100%

conda-24.11.3        | 1.1 MB    | ##################################5   |  93%

python-3.12.2        | 12.5 MB   | ######6                               |  18%

conda-24.11.3        | 1.1 MB    | ##################################### | 100%

python-3.12.2        | 12.5 MB   | #######6                              |  21%
python-3.12.2        | 12.5 MB   | ########6                             |  23%
python-3.12.2        | 12.5 MB   | ##################################### | 100%
openssl-3.5.0        | 2.9 MB    | ##########4                           |  28%
openssl-3.5.0        | 2.9 MB    | ############                          |  33%
openssl-3.5.0        | 2.9 MB    | #############6                        |  37%
openssl-3.5.0        | 2.9 MB    | ################2                     |  44%
openssl-3.5.0        | 2.9 MB    | ##################7                   |  51%
openssl-3.5.0        | 2.9 MB    | #####################7                |  59%
openssl-3.5.0        | 2.9 MB    | ########################5             |  66%
openssl-3.5.0        | 2.9 MB    | ###########################6          |  75%
openssl-3.5.0        | 2.9 MB    | ##############################4       |  82%
openssl-3.5.0        | 2.9 MB    | ################################6     |  88%
openssl-3.5.0        | 2.9 MB    | ##################################### | 100%
openssl-3.5.0        | 2.9 MB    | ##################################### | 100%
























































Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [50]:
import urllib.parse

user = 'root'
password = 'Balaji@12'
host = 'localhost'
port = 3306
database = 'orders'

# Encode special characters in password
encoded_password = urllib.parse.quote_plus(password)

# Create engine (pymysql is used internally by SQLAlchemy)
engine = create_engine(f"mysql+pymysql://{user}:{encoded_password}@{host}:{port}/{database}")

In [51]:
conn = engine.connect()
print("✅ MySQL connected!")
conn.close()

✅ MySQL connected!

In [53]:
df.to_sql('df_orders', con=engine, index=False, if_exists='append')

9994